### PR TITLE
Sns icons

### LINKED ISSUE #40: As a general user, I would like the SNS icon to be displayed somewhere on the page.

### PR DESCRIPTION
**Pull request by MasakiShiraishi**
I forgot to enter the styling code in the src/sections/footer.scss file and also to install npm init to in my local repo for working sass:watch, so I posted the PR again.

### CODE REVIEW

**Review by NelsonTheBrave — APPROVED** [review]
Ok, looks good!

**Review by rl-86 — APPROVED** [review]
👍

**Review by JrSchoolAccount — DISMISSED** [review]
Are you using the extension Prettier?
The formating is off.

image

**Review by NelsonTheBrave — APPROVED** [review]
Yeah formatting of scss was a bit weird, maybe you forgot to auto-format it? I quick fixed it in the github editor for now

**Pull request merged**
