### PR TITLE
SNS icons

### LINKED ISSUE #40: As a general user, I would like the SNS icon to be displayed somewhere on the page.

### PR DESCRIPTION
**Pull request by MasakiShiraishi**
I added 4 SNS icons at the bottom right of the header.

### CODE REVIEW

**Comment by NelsonTheBrave** [comment]
Looks nice! Would be nice though to fix so that we don't get all the css.map files added. Not sure why you get so many of them, for me there's normally only been one for the main.css.
Also, it seems like I cannot "review" this PR for some reason....

**Review by FelixHultman — DISMISSED** [review]
very nice!

**Review by rl-86 — DISMISSED** [review]
Looking good

**Comment by MasakiShiraishi** [comment]
I made delete unnecessary map files that @NelsonTheBrave had written on this page and tried only to add styling code to main.css. 
I hope it works with new version without any problem.

**Review by FelixHultman — APPROVED** [review]
Good work on removing the extra files!

**Comment by MasakiShiraishi** [comment]
I handled a merge conflict.

**Review by NelsonTheBrave — APPROVED** [review]
Good fix!

**Pull request merged**
